### ISSUE TITLE
Errors out on battery_fail.png

### ISSUE THREAD

**Issue by StarkDroid** [B--B/xiaomi_msm8996-common#2]
Considering this is something that's only input by Offline charging, I wasn't able to see any device tree specific Offline charger implementation that should be causing this conflict. Any idea where i should be looking at?

PS. Removing battery_fail.png and battery_scale.png from source vendor does help it but am trying to understand what might be the cause.

Here's the log
build/make/core/Makefile:61: error: overriding commands for target `/home/trishi/corvus/out/target/product/gemini/system/product/etc/res/images/charger/battery_fail.png', previously defined at build/make/core/base_rules.mk:525

**Comment by B--B** [comment]
What ROM are you trying to compile? This seems related to ROM sources. You can suppress that error adding BUILD_BROKEN_DUP_RULES := true to the boardconfig in msm8996-common, but take in consideration the fact that with that flag you lose control over the sources, because both resources will be picked, and the last one will override the first one, not a big problem if it's the battery png, but be sure that it's the only one, other things like libraries or overlays may break things.
Also, there are some other important things:

1 - hardware/xiaomi repo is a dependency for IR HAL, be sure to add the repo to your manifest or the ROM will compile fine, but won't boot (bootloop)
2 - LA.UM.9.6.2.r1-04100-89xx.0 msm8996 QCOM HALs are MANDATORY, the new graphics blobs requires the new display HAL. New blobs with the old HAL breaks surfaceflinger, be careful. Also, take in mind that WFD require libdisplayconfig.qti which is NOT provided in old display HAL repo. If the ROM you are compiling doesn't have that repos you can import them from Pixel Experience repos

If you have other issues, feel free to ask

**Comment by StarkDroid** [comment]
Yes, the mandatory things have been taken care of. Already got the guide through your Pixel Experience XDA thread, "note to developers". Thanks for your prompt help! The build's successfully done. 

If i do bump into any errors or concerning device specific things, will definitely.
Let me close this thread and open up if i find anything new!
